name: update awesome-stars
on:
  schedule:
  - cron: 1 * * * *
jobs:
  build:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: checkout actions
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Set up Python 3.7
      run: |
        python3 -m pip install --upgrade pip
        pip3 install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username hantaotaohan --repository stars --sort --token ${GITHUB_TOKEN} --message 'stars update by github actions cron'
