name: update awesome-stars
on:
  schedule:
  - cron: 1 * * * *
  push:
    branches: 
    - master
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      # - name: 'Install dependencies'
      #   run: python -m pip install --upgrade pip
      - name: 'Install requirements'
        run: |
          pip install starred
      - name: update repo
        env:
          STARS_TOKEN: ${{ secrets.STARS_TOKEN }}
        run: starred --username hantaotaohan --repository stars --sort --token ${STARS_TOKEN} --message 'stars update by github actions cron'
