name: update awesome-stars
on:
  schedule:
  - cron: 1 * * * *
jobs:
  awesome-stars:
    name: update awesome-stars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          path: "${{ github.repository }}"
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip3 install starred
    - name: update repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: starred --username hantaotaohan --repository stars --sort --token ${GITHUB_TOKEN} --message 'stars update by github actions cron'
